language: ruby
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  - vendor
before_install:
- nvm install 6
install:
- npm install
script:
- npm run-script build
env:
- AWS_S3_BUCKET=s3.fightforthefuture.org
branches:
  only:
  - production
before_deploy:
- node scripts/generate_fp_token.js
- scripts/deploy-ghpages.sh
deploy:
  provider: s3
  access_key_id: AKIAJLVMZBFR2W3V2HBA
  secret_access_key:
    secure: njVb7eOpG0PPLZyepddJxILZOv9o/tD3pmi/8t80xzBDnhX3QKWZ5T5VQOxZpw/ti5ix9KXvXczyJdPdUQ9fvaU1rXtD2+HwVd61enKvlpYD/hgvznMN77oSr4imkekcFAr5vJvpzhEBFlGVCHAgLEDsXYICBFUyxAoQ8K5P9XdoeSoH5nxhwb+V1lDNd+RaDJQ9YNcjOqYwUj4RkFYcahfMZgwkEYkDwFcf7hK5gSAoFJHRl+nOGNUtWSz+afgEAGYHRsp0AXbUygWM56W0kzIkMmNw5NB+yjOkyisGQ8eUvrHL0TGU3PCJqAt6QQftzX1D/FvcIxlzluF+9dGRW4aNDL/BTrklU1b7QcEOqgHc+0WUYPfJ9FTIV8zGu25QPD6YYYqpvGY2rsP94SrTpqmD0N0HRu/MfhFmX05P0pWov8YhhASoQExlAqdHUFefjRp/MfV/xDOhimZis+qGMCJByEWFdfutn+d899yxdeCNGVqsnYcuLbg1W3U+SZlZXX2lWvUVfV7gKcgkFqj4Qt2X+VikrqwxleWDPhIOHnj4xN1ut0eRyYUcV+PbolKfT2wjtoXjsxf94f90QAEghM7FTNgvHif/v8FMI5icUYNOzl5zj/ZyXX5XhBUNpfqfI6UO3/CzI8enCOMg/1xO497W2wYIynvy9HTK5cBr5WY=
  bucket: s3.fightforthefuture.org
  local-dir: assets
  upload-dir: 2017pledge
  skip_cleanup: true
  acl: public_read
  on:
    repo: fightforthefuture/2017Pledge
    branch: production
